### ISSUE TITLE
kamerka gui displayed but it doesn't pull search queires.

### ISSUE THREAD

**Issue by tellmenot** [woj-ciech/Kamerka-GUI#11]
I pasted the api keys in keys.json file and i had an canerra error so i just ran the redis-server and then i opened up  the local host in **http** not in an https and where **kamerka gui** is found when i used the search after providing the queries i found **no result in the gui**  if anyone found same issue help me out in this.
![Screenshot from 2020-03-04 16-18-38](https://user-images.githubusercontent.com/61781756/75872269-dbab4880-5e33-11ea-8fe9-d6d1f3c18cfc.png)
![Screenshot from 2020-03-04 16-19-25](https://user-images.githubusercontent.com/61781756/75872320-f2519f80-5e33-11ea-8913-8ba470274d1a.png)

**Comment by woj-ciech** [comment]
try to run celery worker inside main directory

**Comment by AdMiZaSa** [comment]
Does anyone know a fix for this as i am getting the same issues?

I am running celery in the main Kamerka directory.

aw******@aw******-Satellite-Pro-L500:~$ cd Kamerka-GUI
aw******@aw******-Satellite-Pro-L500:~/Kamerka-GUI$ ls
app_kamerka  db.sqlite3  keys.json  queries.md  requirements.txt
_config.yml  kamerka     manage.py  README.md
awootton@awootton-Satellite-Pro-L500:~/Kamerka-GUI$ celery worker -A kamerka --loglevel=info
 
 -------------- celery@aw******-Satellite-Pro-L500 v4.4.2 (cliffs)
--- ***** ----- 
-- ******* ---- Linux-4.15.0-159-generic-x86_64-with-Ubuntu-18.04-bionic 2021-11-10 13:57:20
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         kamerka:0x7f4e743d38d0
- ** ---------- .> transport:   redis://localhost:6379//
- ** ---------- .> results:     redis://localhost:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . kamerka.celery.debug_task
  . kamerka.tasks.binary_edge_scan
  . kamerka.tasks.bosch_usernames
  . kamerka.tasks.devices_nearby
  . kamerka.tasks.flickr
  . kamerka.tasks.nmap_scan
  . kamerka.tasks.send_to_field_agent_task
  . kamerka.tasks.shodan_scan_task
  . kamerka.tasks.shodan_search
  . kamerka.tasks.twitter_nearby_task
  . kamerka.tasks.whoisxml

[2021-11-10 13:57:20,834: INFO/MainProcess] Connected to redis://localhost:6379//
[2021-11-10 13:57:20,843: INFO/MainProcess] mingle: searching for neighbors
[2021-11-10 13:57:21,864: INFO/MainProcess] mingle: all alone
[2021-11-10 13:57:21,895: WARNING/MainProcess] /home/awootton/.local/lib/python3.6/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  leak, never use this setting in production environments!''')
[2021-11-10 13:57:21,895: INFO/MainProcess] celery@awootton-Satellite-Pro-L500 ready.
[2021-11-10 13:59:37,092: INFO/MainProcess] Received task: kamerka.tasks.shodan_search[f1fbbce3-3965-4393-b4e0-97bbe03b30c8]  
[2021-11-10 13:59:37,094: WARNING/ForkPoolWorker-4] port:18245,18246 product:"general electric"
[2021-11-10 13:59:42,387: WARNING/ForkPoolWorker-4] fail1, sleeping...
[2021-11-10 13:59:52,557: WARNING/ForkPoolWorker-4] Invalid API key
[2021-11-10 14:00:02,726: WARNING/ForkPoolWorker-4] Invalid API key
[2021-11-10 14:00:13,261: WARNING/ForkPoolWorker-4] Invalid API key
[2021-11-10 14:00:13,261: WARNING/ForkPoolWorker-4] 'bool' object is not subscriptable


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Redis is running on a separate terminal:

aw******@aw******-Satellite-Pro-L500:~/Desktop$ cd Kamerka-GUI-master
aw******@aw******-Satellite-Pro-L500:~/Desktop/Kamerka-GUI-master$ redis-server
20421:C 10 Nov 14:36:11.050 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
20421:C 10 Nov 14:36:11.050 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=20421, just started
20421:C 10 Nov 14:36:11.050 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
20421:M 10 Nov 14:36:11.052 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
20421:M 10 Nov 14:36:11.052 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
20421:M 10 Nov 14:36:11.052 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
20421:M 10 Nov 14:36:11.052 # Creating Server TCP listening socket *:6379: bind: Address already in use
aw******@aw******-Satellite-Pro-L500:~/Desktop/Kamerka-GUI-master$ 


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

And the server is running and I can connect to local host using HTTP:

aw******@aw******-Satellite-Pro-L500:~/Desktop/Kamerka-GUI-master$ python3 manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified some issues:

WARNINGS:
?: (2_0.W001) Your URL pattern '^celery-progress/' has a route that contains '(?P<', begins with a '^', or ends with a '$'. This was likely an oversight when migrating to django.urls.path().

System check identified 1 issue (0 silenced).
November 10, 2021 - 13:48:35
Django version 2.2.7, using settings 'kamerka.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[10/Nov/2021 13:58:44] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03hÂ\xad\x13Öß\x1fìf¹àö£]´µ\x1e\x11bÔçNvîöäq\x1dÞÉ\x87ª Â\x841D\x1aù\x18\x04j#\x03ù\x9cù\xadb\x80\x91óÇ®ür`V:«È¦oö\xa0\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
[10/Nov/2021 13:58:44] You're accessing the development server over HTTPS, but it only supports HTTP.


-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

However, when I search I get zero results as shown in the attached screengrab.
![Screenshot from 2021-11-11 09-32-29](https://user-images.githubusercontent.com/48198197/141274235-a841036b-aac7-4b9c-9304-7d69980dfc6f.png)


I know my Shodan key is fine as it works with KamerkaFIST.  I don't understand why I get the message Success! at the top left hand side of the page after a search but not results are shown.

Can anyone offer advice

Thanks in advance.

**Comment by NIFSEC** [comment]
Same issues here 
I'm running it all in the main directory ND still not getting any results from the queries
